name: Fetch Air Quality Data

on:
  schedule:
    # Runs at 00:00 UTC every day (4:00 PM PST / 5:00 PM PDT)
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD). If not provided, uses end_date - days_back'
        required: false
      end_date:
        description: 'End date (YYYY-MM-DD). Defaults to today'
        required: false
      days_back:
        description: 'Number of days of historical data to fetch (used if start_date not provided)'
        required: false
        default: '1'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    env:
      PYTHON_VERSION: '3.11'
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for git diff to work properly
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas requests python-dotenv
    
    - name: Fetch historical data
      id: fetch
      run: |
        # Set end date (default to today)
        if [ -z "${{ github.event.inputs.end_date }}" ]; then
          END_DATE=$(date +'%Y-%m-%d')
          echo "Using end date: $END_DATE"
        else
          END_DATE="${{ github.event.inputs.end_date }}"
          echo "Using provided end date: $END_DATE"
        fi
        
        # Set start date based on input or calculate from days_back
        if [ -n "${{ github.event.inputs.start_date }}" ]; then
          START_DATE="${{ github.event.inputs.start_date }}"
          echo "Using provided start date: $START_DATE"
        else
          DAYS_BACK=${{
            github.event.inputs.days_back || '1'
          }}
          START_DATE=$(date -d "$END_DATE - $DAYS_BACK days" +'%Y-%m-%d')
          echo "Calculated start date: $START_DATE (end date - $DAYS_BACK days)"
        fi
        
        # Validate dates
        if [[ "$START_DATE" > "$END_DATE" ]]; then
          echo "Error: Start date ($START_DATE) is after end date ($END_DATE)"
          exit 1
        fi
        
        echo "Fetching data from $START_DATE to $END_DATE"
        python -c "
        from fetch_historical_data import fetch_historical_data
        from datetime import datetime
        
        # Convert dates to datetime objects for validation
        start = datetime.strptime('$START_DATE', '%Y-%m-%d')
        end = datetime.strptime('$END_DATE', '%Y-%m-%d')
        
        # Calculate max allowed start date (2 years back from today)
        max_days_back = 730  # ~2 years
        max_start_date = datetime.now() - datetime.timedelta(days=max_days_back)
        
        if start < max_start_date:
            print(f'Warning: Start date is more than {max_days_back} days in the past. Data might not be available.')
            print(f'Setting start date to: {max_start_date.strftime(\"%Y-%m-%d\")}')
            start = max_start_date
        
        fetch_historical_data(
            start_date=start.strftime('%Y-%m-%d'),
            end_date=end.strftime('%Y-%m-%d'),
            output_file='training_data.csv'
        )"
    
    - name: Check for data changes
      id: git-check
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Check if there are any changes
        if git diff --exit-code training_data.csv; then
          echo "No changes detected in the data"
        else
          echo "changes_detected=true" >> $GITHUB_OUTPUT
          echo "Changes detected in the data"
        fi
        
    - name: Commit and push changes
      if: steps.git-check.outputs.changes_detected == 'true'
      run: |
        git add training_data.csv
        git commit -m "[Automated] Update air quality data (${{ github.event.inputs.start_date || 'auto' }} to ${{ github.event.inputs.end_date || 'today' }})"
        git push
    
    - name: Output date range info
      run: |
        echo "Data fetch completed for range: ${{ steps.fetch.outputs.START_DATE }} to ${{ steps.fetch.outputs.END_DATE }}"
        echo "Changes detected: ${{ steps.git-check.outputs.changes_detected || 'false' }}"
    
    - name: Trigger model retraining (optional)
      if: steps.git-check.outputs.changes_detected == 'true' && github.event_name == 'schedule'
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'train_model.yml',
            ref: 'main'
          })
    
    - name: Create PR if needed (optional)
      if: steps.git-check.outputs.changes_detected == 'true' && github.event_name == 'schedule'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "[Automated] Update air quality data (${{ github.event.inputs.start_date || 'auto' }} to ${{ github.event.inputs.end_date || 'today' }})"
        title: "[Data Update] New air quality data (${{ github.event.inputs.start_date || 'auto' }} to ${{ github.event.inputs.end_date || 'today' }})"
        body: "Automated update of air quality data"
        branch: "data/update-$(date +%s)"
